package proxy;

import ws.Account;
import ws.AccountService;
import ws.AccountService_Service;

import java.util.List;
import java.util.concurrent.atomic.AtomicInteger;

public class AccountProxyClient {
    public static void main(String[] args) {
        AccountService accountServiceProxy = new AccountService_Service().getAccountServicePort();
        //WE SEND TO OUR STUB (GENERATED BY <<wsimport URL-WSDL -s .>> using a wsdl of the JAX-WS server)
        //THAT WE NEED TO CALL A SERVICE OF ANOTHER APPLICATION (SERVER - VIA THE SKELETON JAX-WS/JAX-B)
        //THEN RETURN THE RESULT OF THE SERVICE
        //THIS IS A COMPLETE ABSTRACTION OF THE WEB-SERVICES ASPECT
        System.out.println(accountServiceProxy.conversion(10));
        //GET ACCOUNT
        Account account = accountServiceProxy.getAccount(1L);
        System.out.println("--------------------------------------------------------------------------");
        System.out.println("ACCOUNT INFOS :");
        System.out.println("CODE : "+account.getId());
        System.out.println("SOLDE : "+account.getSolde());
        System.out.println("ACTIVATED : "+account.isActivated());
        System.out.println("--------------------------------------------------------------------------");
        //LIST OF ACCOUNTS
        List<Account> accounts = accountServiceProxy.getAll();
        AtomicInteger i = new AtomicInteger();
        System.out.println("LIST OF ACCOUNTS");
        System.out.println("--------------------------------------------------------------------------");
        accounts.stream().forEach(acc -> {
            System.out.println("ACCOUNT "+(i.getAndIncrement())+" :");
            System.out.println("CODE : "+acc.getId());
            System.out.println("SOLDE : "+acc.getSolde());
            System.out.println("ACTIVATED : "+acc.isActivated());
            System.out.println("--------------------------------------------------------------------------");
        });
    }
}
