
package ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AccountService", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AccountService {


    /**
     * 
     * @param mt
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "conversion", targetNamespace = "http://ws/", className = "ws.Conversion")
    @ResponseWrapper(localName = "conversionResponse", targetNamespace = "http://ws/", className = "ws.ConversionResponse")
    @Action(input = "http://ws/AccountService/conversionRequest", output = "http://ws/AccountService/conversionResponse")
    public double conversion(
        @WebParam(name = "mt", targetNamespace = "")
        double mt);

    /**
     * 
     * @param id
     * @return
     *     returns ws.Account
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccount", targetNamespace = "http://ws/", className = "ws.GetAccount")
    @ResponseWrapper(localName = "getAccountResponse", targetNamespace = "http://ws/", className = "ws.GetAccountResponse")
    @Action(input = "http://ws/AccountService/getAccountRequest", output = "http://ws/AccountService/getAccountResponse")
    public Account getAccount(
        @WebParam(name = "id", targetNamespace = "")
        Long id);

    /**
     * 
     * @return
     *     returns java.util.List<ws.Account>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAll", targetNamespace = "http://ws/", className = "ws.GetAll")
    @ResponseWrapper(localName = "getAllResponse", targetNamespace = "http://ws/", className = "ws.GetAllResponse")
    @Action(input = "http://ws/AccountService/getAllRequest", output = "http://ws/AccountService/getAllResponse")
    public List<Account> getAll();

}
